### ISSUE TITLE
Need a working demo

### ISSUE THREAD

**Issue by shiquanwang** [intel/light-model-transformer#1]
Tried with frozen mobile net from tensorflow/models repo.
Can't go through all steps.

**Comment by jackywei** [comment]
We should support the mobilenet, we did not found any issue in our side before, so what's your TF version you are using? and could you please also share the repo for the model inside the TF? we will try to reproduce the issue ASAP. meanwhile, if you want to build a demo, could you please also try other topology? like resnet or googlenet? should be ok on those too.

**Comment by heagoo** [comment]
For mobilenet, there is an OP named Relu6, previously we indeed have such support by patching MKLDNN. But then we found a better solution is to use eltwise_bounded_relu without patching it. now working on it and will update the code.

**Comment by shiquanwang** [comment]
@jackywei 
Thanks.
I was using Tensorflow 1.9 to test.
The model `MobileNet_v1_1.0_224` is from `https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md`.
The download link of the model is: `http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224.tgz`

@heagoo nice idea, thanks.

**Comment by rfsaliev** [comment]
outdated
